version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "220MB"